#ifndef PYASYNCHIO_DETAIL_CONFIG_HPP_INCLUDED_
#define PYASYNCHIO_DETAIL_CONFIG_HPP_INCLUDED_

#pragma once

#ifdef PYASYNCHIO_DYNAMIC

#ifdef PYASYNCHIO_BUILD
#define PYASYNCHIO_LINK_DECL __declspec(dllexport)
#else // PYASYNCHIO_BUILD
#define PYASYNCHIO_LINK_DECL __declspec(dllimport)
#endif // PYASYNCHIO_BUILD

#else // PYASYNCHIO_DYNAMIC

#define PYASYNCHIO_LINK_DECL

#endif // PYASYNCHIO_DYNAMIC


#endif // PYASYNCHIO_DETAIL_CONFIG_HPP_INCLUDED_