#define PYASYNCHIO_BOOST_SIGNAL_WRAPPER_ARITY 4
#define PYASYNCHIO_BOOST_SIGNAL_WRAPPER_TYPED_ARGUMENTS typename s::arg1_type t1, typename s::arg2_type t2, typename s::arg3_type t3, typename s::arg4_type t4
#define PYASYNCHIO_BOOST_SIGNAL_WRAPPER_ARGUMENTS t1, t2, t3, t4

#include "signal_wrapper.hpp"

#undef PYASYNCHIO_BOOST_SIGNAL_WRAPPER_ARITY
#undef PYASYNCHIO_BOOST_SIGNAL_WRAPPER_TYPED_ARGUMENTS
#undef PYASYNCHIO_BOOST_SIGNAL_WRAPPER_ARGUMENTS