#define PYASYNCHIO_BOOST_SIGNAL_WRAPPER_ARITY 2
#define PYASYNCHIO_BOOST_SIGNAL_WRAPPER_TYPED_ARGUMENTS typename s::arg1_type t1, typename s::arg2_type t2
#define PYASYNCHIO_BOOST_SIGNAL_WRAPPER_ARGUMENTS t1, t2

#include "signal_wrapper.hpp"

#undef PYASYNCHIO_BOOST_SIGNAL_WRAPPER_ARITY
#undef PYASYNCHIO_BOOST_SIGNAL_WRAPPER_TYPED_ARGUMENTS
#undef PYASYNCHIO_BOOST_SIGNAL_WRAPPER_ARGUMENTS