#define PYASYNCHIO_BOOST_SIGNAL_WRAPPER_ARITY 1
#define PYASYNCHIO_BOOST_SIGNAL_WRAPPER_TYPED_ARGUMENTS typename s::arg1_type t1
#define PYASYNCHIO_BOOST_SIGNAL_WRAPPER_ARGUMENTS t1

#include "signal_wrapper.hpp"

#undef PYASYNCHIO_BOOST_SIGNAL_WRAPPER_ARITY
#undef PYASYNCHIO_BOOST_SIGNAL_WRAPPER_TYPED_ARGUMENTS
#undef PYASYNCHIO_BOOST_SIGNAL_WRAPPER_ARGUMENTS