#define SPACE_TRANSPORT_BOOST_SIGNAL_WRAPPER_ARITY 3
#define SPACE_TRANSPORT_BOOST_SIGNAL_WRAPPER_TYPED_ARGUMENTS typename s::arg1_type t1, typename s::arg2_type t2, typename s::arg3_type t3
#define SPACE_TRANSPORT_BOOST_SIGNAL_WRAPPER_ARGUMENTS t1, t2, t3

#include "signal_wrapper.hpp"

#undef SPACE_TRANSPORT_BOOST_SIGNAL_WRAPPER_ARITY
#undef SPACE_TRANSPORT_BOOST_SIGNAL_WRAPPER_TYPED_ARGUMENTS
#undef SPACE_TRANSPORT_BOOST_SIGNAL_WRAPPER_ARGUMENTS